spring:
  profiles.active: default

---

spring:
  profiles: default


---

spring:
  profiles: prod
spring.main.banner-mode: "off"
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/domaindriven?autoReconnect=true
  username: root
  password:

